In [2]:
# import numpy libarary
import numpy as np

# Creating an array with numpy

In [4]:
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [8]:
len(food)

3

In [11]:
prices[2]

5

In [12]:
prices.mean()

5.0

In [15]:
price = np.array([3,4,5])
price.mean()

4.0

In [18]:

np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.arange(2,14, 2)

array([ 2,  4,  6,  8, 10, 12])

In [30]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

# Array Functions

In [38]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a


array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [39]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [40]:
b = np.array([10.2, 3.4, 53.6, 92.6, 45.5])
b

array([10.2,  3.4, 53.6, 92.6, 45.5])

In [45]:

np.concatenate((a, b))

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  92.6,  45.5])

# 2-D Arrays

In [47]:
a = np.array([[1,2,3,4,5], [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [50]:
b = np.array([[6,7,5,4,3],[8,9,7,6,5]])
b

array([[6, 7, 5, 4, 3],
       [8, 9, 7, 6, 5]])

In [65]:
b.ndim

2

In [52]:
c = np.concatenate((a, b))
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 5, 4, 3],
       [8, 9, 7, 6, 5]])

In [53]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 5, 4, 3],
       [8, 9, 7, 6, 5]])

In [54]:
c = np.concatenate((a, b), axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7, 5, 4, 3],
       [5, 4, 3, 2, 1, 8, 9, 7, 6, 5]])

In [62]:
x = np.array([[[0,1,2,3,],
               [4,5,6,7]],
              
              [[0,1,2,3],
              [4,5,6,7]],
              [[0,1,2,3],
              [4,5,6,7]]])
x

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [63]:
x.ndim

3

In [67]:
b = np.array([[5,6,7],
             [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [68]:
b.ndim

2